<?php

declare(strict_types=1);

namespace Tpetry\MysqlExplain\Values;

/**
 * @internal
 *
 * @phpstan-type ExplainTraditional array<int, mixed>
 * @phpstan-type Warnings array<int, mixed>
 */
class QueryMetrics
{
    /**
     * The EXPLAIN FORMAT=JSON output.
     */
    private string $explainJSON;

    /**
     * The EXPLAIN FORMAT=TRADITIONAL output.
     *
     * @type ExplainTraditional
     */
    private array $explainTraditional;

    /**
     * The EXPLAIN FORMAT=TREE output.
     */
    private ?string $explainTree;

    /**
     * The query that generated the metrics.
     */
    private string $query;

    /**
     * The database version the executed was executed on.
     */
    private string $version;

    /**
     * The query metrics generated by SHOW WARNINGS.
     *
     * @type Warnings
     */
    private ?array $warnings;

    /**
     * @param  ExplainTraditional  $explainTraditional
     * @param  Warnings  $warnings
     */
    public function __construct(
        string $query,
        string $version,
        array $explainTraditional,
        string $explainJson,
        ?string $explainTree = null,
        ?array $warnings = null,
    ) {
        $this->query = $query;
        $this->version = $version;
        $this->explainTraditional = $explainTraditional;
        $this->explainJSON = $explainJson;
        $this->explainTree = $explainTree;
        $this->warnings = $warnings;
    }

    public function getExplainJson(): string
    {
        return $this->explainJSON;
    }

    /**
     * @return ExplainTraditional
     */
    public function getExplainTraditional(): array
    {
        return $this->explainTraditional;
    }

    public function getExplainTree(): ?string
    {
        return $this->explainTree;
    }

    public function getQuery(): string
    {
        return $this->query;
    }

    public function getVersion(): string
    {
        return $this->version;
    }

    /**
     * @return Warnings
     */
    public function getWarnings(): ?array
    {
        return $this->warnings;
    }
}
